env:
  browser: true
  es6: true
  node: true
extends:
  - airbnb-base
parser: babel-eslint
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaVersion: 6
  sourceType: module
  ecmaFeatures: {
    jsx: true
  }
rules: {
  import/prefer-default-export: false
}
